/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nguyenvantien.csm.view;

import com.nguyenvantien.csm.api.CategoryApi;
import com.nguyenvantien.csm.api.ItemApi;
import com.nguyenvantien.csm.model.Item;
import com.nguyenvantien.csm.model.SpinnerEditor;
import com.nguyenvantien.csm.utils.StringUtils;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() throws IOException {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        setCategory();
        setTable();
        
    }
    private void setCategory() throws IOException{
        DefaultListModel listModel;
        listModel = new DefaultListModel();
        List<Object> lists = CategoryApi.getAllCategory();
        for (int i = 0; i < lists.size(); i++) {
            listModel.add(i, lists.get(i).toString());
        }
        categoryList.setModel(listModel);
    }
    private void setTable() throws IOException{
        List<Item> lists = ItemApi.getAllItem();
        DefaultTableModel defaultTableModel = (DefaultTableModel) listsItemTb.getModel();
        for (int i = 0; i < lists.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                lists.get(i).getName(),
                StringUtils.formatMoney(lists.get(i).getPrice().toString()),
                lists.get(i).getUnit(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bill = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        billTb = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        discountSp = new javax.swing.JSpinner();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        upQuantityBt = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        addItemBt = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        items = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchTf = new javax.swing.JTextField();
        searchBt = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listsItemTb = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.X_AXIS));

        bill.setBackground(new java.awt.Color(255, 255, 255));
        bill.setPreferredSize(new java.awt.Dimension(600, 320));
        bill.setLayout(new javax.swing.BoxLayout(bill, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setBackground(new java.awt.Color(51, 255, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(344, 300));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Hóa Đơn");
        jPanel7.add(jLabel3);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        billTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        billTb.setRowHeight(30);
        jScrollPane3.setViewportView(billTb);
        if (billTb.getColumnModel().getColumnCount() > 0) {
            billTb.getColumnModel().getColumn(1).setMinWidth(80);
            billTb.getColumnModel().getColumn(1).setPreferredWidth(80);
            billTb.getColumnModel().getColumn(1).setMaxWidth(80);
            billTb.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        jPanel9.add(jScrollPane3);

        jPanel7.add(jPanel9);

        bill.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 199, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 145, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(255, 153, 153));
        jPanel11.setForeground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setLayout(new java.awt.GridLayout(1, 2));

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Tiền hàng:");
        jPanel18.add(jLabel5);

        jPanel12.add(jPanel18);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel6.setText("0");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel16.add(jLabel6);

        jPanel12.add(jPanel16);

        jPanel11.add(jPanel12);

        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("Giảm:");
        jPanel20.add(jLabel8);

        jPanel19.add(jPanel20);

        jPanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        jPanel21.add(discountSp);

        jPanel19.add(jPanel21);

        jPanel11.add(jPanel19);

        jPanel22.setLayout(new java.awt.GridLayout(1, 2));

        jPanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel12.setText("Thành tiền:");
        jPanel23.add(jLabel12);

        jPanel22.add(jPanel23);

        jPanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel13.setText("0");
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel24.add(jLabel13);

        jPanel22.add(jPanel24);

        jPanel11.add(jPanel22);

        jPanel13.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        jButton2.setText("Thanh toán");
        jPanel13.add(jButton2);

        jButton3.setText("Hủy");
        jPanel13.add(jButton3);

        jPanel11.add(jPanel13);

        jPanel8.add(jPanel11);

        bill.add(jPanel8);

        getContentPane().add(bill);

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel14.setMaximumSize(new java.awt.Dimension(80, 32767));
        jPanel14.setMinimumSize(new java.awt.Dimension(80, 0));
        jPanel14.setLayout(new java.awt.GridLayout(3, 1));

        jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel29);

        upQuantityBt.setText("Tăng++");
        upQuantityBt.setMaximumSize(new java.awt.Dimension(120, 21));
        upQuantityBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upQuantityBtActionPerformed(evt);
            }
        });
        jPanel15.add(upQuantityBt);

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel30);

        jButton8.setText("Giảm - -");
        jButton8.setMaximumSize(new java.awt.Dimension(120, 21));
        jPanel15.add(jButton8);

        jPanel14.add(jPanel15);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel27);

        jButton6.setText("Xóa >>");
        jButton6.setMaximumSize(new java.awt.Dimension(120, 21));
        jPanel17.add(jButton6);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel28);

        addItemBt.setText("<< Thêm");
        addItemBt.setMaximumSize(new java.awt.Dimension(120, 21));
        addItemBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtActionPerformed(evt);
            }
        });
        jPanel17.add(addItemBt);

        jPanel14.add(jPanel17);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel25);

        getContentPane().add(jPanel14);

        items.setMaximumSize(new java.awt.Dimension(400, 65609));
        items.setLayout(new javax.swing.BoxLayout(items, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(135, 40));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setText("  Tìm kiếm:    ");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 13));
        jPanel1.add(jLabel1);

        searchTf.setColumns(50);
        jPanel1.add(searchTf);

        searchBt.setText("Tìm");
        searchBt.setMaximumSize(new java.awt.Dimension(21, 71));
        searchBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtActionPerformed(evt);
            }
        });
        jPanel1.add(searchBt);

        items.add(jPanel1);

        jPanel4.setBackground(new java.awt.Color(51, 255, 153));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 68));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Các loại đồ dùng");
        jPanel5.add(jLabel2);

        jPanel4.add(jPanel5);

        jPanel26.setMinimumSize(new java.awt.Dimension(23, 100));
        jPanel26.setPreferredSize(new java.awt.Dimension(204, 100));
        jPanel26.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setMaximumSize(new java.awt.Dimension(32767, 122));

        categoryList.setMaximumSize(new java.awt.Dimension(32, 55));
        categoryList.setMinimumSize(new java.awt.Dimension(32, 55));
        categoryList.setPreferredSize(new java.awt.Dimension(32, 55));
        categoryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categoryList);

        jPanel26.add(jScrollPane1);

        jPanel4.add(jPanel26);

        items.add(jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 105));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Danh sách đồ dùng");
        jPanel3.add(jLabel4);

        jPanel2.add(jPanel3);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        listsItemTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên", "Giá", "Đơn vị"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listsItemTb);

        jPanel6.add(jScrollPane2);

        jPanel2.add(jPanel6);

        items.add(jPanel2);

        getContentPane().add(items);

        jMenuBar1.setMaximumSize(new java.awt.Dimension(64, 60));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(64, 20));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryListMouseClicked
        try {
            // TODO add your handling code here:
            List<Item> lists = ItemApi.getItemsByCategory(categoryList.getSelectedValue());
            setTable(lists);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(categoryList.getSelectedValue());
    }//GEN-LAST:event_categoryListMouseClicked

    private void searchBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtActionPerformed
        try {
            List<Item> lists = ItemApi.getItemsByName(searchTf.getText());
            setTable(lists);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtActionPerformed

    private void addItemBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtActionPerformed
        // TODO add your handling code here:
        int indexOfItem = listsItemTb.getSelectedRow();
        if(indexOfItem>=0){
            String name = (String) listsItemTb.getValueAt(indexOfItem, 0);
            String price = (String) listsItemTb.getValueAt(indexOfItem, 1);
            addRowBillTable(name, price);
        }
    }//GEN-LAST:event_addItemBtActionPerformed

    private void upQuantityBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upQuantityBtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upQuantityBtActionPerformed

    private void addRowBillTable(String name, String price){
        DefaultTableModel defaultTableModel = (DefaultTableModel) billTb.getModel();
        int index = checkNameInBill(name);
        if(index >= 0){
            Integer newQuantity = Integer.parseInt(defaultTableModel.getValueAt(index, 1).toString()) + 1;
            Double total = StringUtils.toValue(defaultTableModel.getValueAt(index, 2).toString())*newQuantity;
            defaultTableModel.setValueAt(newQuantity, index, 1);
            defaultTableModel.setValueAt(StringUtils.formatMoney(total.toString()), index, 3);
        } else{
            defaultTableModel.addRow(new Object[]{
            name,
            1,
            price,
            price
        });
        }
        
    }
    
    private int checkNameInBill(String name){
        for (int i = 0; i < billTb.getRowCount(); i++) {
            if(billTb.getValueAt(i, 0).equals(name)){
                return i;
            }
        }
        return -1;
    }
    
    private void setTable(List<Item> lists){
        DefaultTableModel defaultTableModel = (DefaultTableModel) listsItemTb.getModel();
        defaultTableModel.getDataVector().removeAllElements();
        for (int i = 0; i < lists.size(); i++) {
            defaultTableModel.addRow(new Object[]{
                lists.get(i).getName(),
                StringUtils.formatMoney(lists.get(i).getPrice().toString()),
                lists.get(i).getUnit(),
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Home().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBt;
    private javax.swing.JPanel bill;
    private javax.swing.JTable billTb;
    private javax.swing.JList<String> categoryList;
    private javax.swing.JSpinner discountSp;
    private javax.swing.JPanel items;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listsItemTb;
    private javax.swing.JButton searchBt;
    private javax.swing.JTextField searchTf;
    private javax.swing.JButton upQuantityBt;
    // End of variables declaration//GEN-END:variables
}
